# Generated by Django 4.2.4 on 2023-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Objec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("picture", models.CharField(max_length=40)),
                ("sound", models.CharField(max_length=40)),
                ("ident", models.BooleanField(default=True)),
            ],
        ),
    ]
