# Generated by Django 4.2.4 on 2023-08-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Item", "0002_grup_objec_grup"),
    ]

    operations = [
        migrations.AddField(
            model_name="grup", name="slug", field=models.SlugField(default=""),
        ),
        migrations.AddField(
            model_name="objec", name="slug", field=models.SlugField(default=""),
        ),
    ]
