# Generated by Django 4.2.4 on 2023-08-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Item", "0003_grup_slug_objec_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grup",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
    ]
